[package]
name = "baandit"
version = "0.1.0"
authors = ["Daniel Hauser <daniel.hauser@liwest.at>"]
edition = "2018"

[dependencies]
font-kit = "0.10.0"
glfw = "0.41.0"
lazy_static = "1.4.0"
notify = "4.0.15"

[build-dependencies]
gl_generator = "0.14.0"